### PR TITLE
[DP-272] Use correct url in login redirect

### PR DESCRIPTION
**Pull request by kozajaku**
- replace `getLoginProxyUrl` call for custom `getLoginUrl` that uses
  `/iam/login` redirect path

# For all changes

- [ ] Ensure adequate tests are in place (or reviewed existing tests cover changes)

# Only if submitting a visual change

- [ ] Ensure to attach screenshots
- [ ] Ensure to have UX team confirm screenshots

### CODE REVIEW

**Comment by weaverjess** [comment]
Looks like a good start- I think it needs to be aware of enterprise slugs/subdomains, and path parmas though- we can duplicate the original function

```
/**
 * Given either an `enterpriseSlug` or an `enterpriseCustomerInviteKey`, returns a
 * URL to the dojo-auth-mfe. This is enterprise specific and aware
 *
 * @param {string} enterpriseSlug Slug of an enterprise customer
 * @param {string} enterpriseCustomerInviteKey UUID of an EnterpriseCustomerInviteKey
 * @returns URL of the enterprise proxy login page in the LMS.
 */
// eslint-disable-next-line import/prefer-default-export
export const getProxyLoginUrl = (enterpriseSlug, enterpriseCustomerInviteKey) => {
  const queryParams = new URLSearchParams();
  queryParams.append('next', global.location);
  if (enterpriseSlug) {
    queryParams.append('enterprise_slug', enterpriseSlug);
  }
  if (enterpriseCustomerInviteKey) {
    queryParams.append('enterprise_customer_invite_key', enterpriseCustomerInviteKey);
  }
  const proxyLoginUrl = `${process.env.LMS_BASE_URL}/enterprise/proxy-login/?${queryParams.toString()}`;
  return proxyLoginUrl;
};
```

**Comment by Alain1405** [comment]
> Looks like a good start- I think it needs to be aware of enterprise slugs/subdomains, and path parmas though- we can duplicate the original function a bit more.
> 
> ```
> /**
>  * Given either an `enterpriseSlug` or an `enterpriseCustomerInviteKey`, returns a
>  * URL to the dojo-auth-mfe. This is enterprise specific and aware
>  *
>  * @param {string} enterpriseSlug Slug of an enterprise customer
>  * @param {string} enterpriseCustomerInviteKey UUID of an EnterpriseCustomerInviteKey
>  * @returns URL of the enterprise proxy login page in the LMS.
>  */
> // eslint-disable-next-line import/prefer-default-export
> export const getProxyLoginUrl = (enterpriseSlug, enterpriseCustomerInviteKey) => {
>   const queryParams = new URLSearchParams();
>   queryParams.append('next', global.location);
>   if (enterpriseSlug) {
>     queryParams.append('enterprise_slug', enterpriseSlug);
>   }
>   if (enterpriseCustomerInviteKey) {
>     queryParams.append('enterprise_customer_invite_key', enterpriseCustomerInviteKey);
>   }
>   const loginUrl = `${process.env.LMS_BASE_URL}/iam/login/?${queryParams.toString()}`;
>   return loginUrl;
> };
> ```
> 
> There are maybe two cases where we may redirect though:
> 
> 1. The user came to the learner portal on a subdomain
> 2. The user came to it without a subdomain? <= I'm not positive on this one
> 
> We might need to make sure the function above knows which pattern it is, and then appends the subdomain correctly.
> 
> @OlhaShyliaieva or @vlad-zherebkin-wp or @alain-scialoja-wp can maybe provide some more context here- I don't know so much about this part of our stack yet since I've only worked on auth.

This really is an onboarding squad decision, but the approach in the PR would always work. 
It is not documented anywhere that  if we try to hit an enterprise URL then we should redirect the user to the login url of that enterprise @weaverjess . I think we can merge this and then create a decision ticket for that behaviour.

**Comment by weaverjess** [comment]
Sorry to clarify, to my knowledge this LMS MFE will never bee seen unless we are are on an enteprise subdomain. I want to confirm this before I make a decision, and think this is something courseware would know.

From an onboarding stand point, if we're on an enterprise subdomain and being redirect, I want it to redirect it to that enterprise subdomain login experience. UX wise I do not want to force the user to re-pick their enterprise when they are coming from one.

@Alain1405

**Comment by Alain1405** [comment]
> Sorry to clarify, to my knowledge this LMS MFE will never bee seen unless we are are on an enterprise subdomain. I want to confirm this before I make a decision, and think this is something courseware would know.

The branded login experience will be seen with direct links, for instance on bookmarks or onboarding emails. If the user starts from the generic experience, they will also be redirected to the branding experience. Isn't it the case?

> From an onboarding stand point, if we're on an enterprise subdomain and being redirect, I want it to redirect it to that enterprise subdomain login experience. UX wise I do not want to force the user to re-pick their enterprise when they are coming from one....

The only question is whether the user should know that such an enterprise exists. But I guess they can also check by typying the url of the branded login.

> So from a decision making stand point I'm kind of there already. Based on the outcome of the above question though, we might actually ONLY need to support enterprise subdomains.
> @Alain1405

That's great. Now the question is, is this a fix to do as part of QA or a never documented feature to implement on a separated ticket @weaverjess ?

**Comment by weaverjess** [comment]
Ack, I lost the reply I typed up. What I wanted to confirm was that this MFE is ONLY served from `<subdomain>.dojoalpha.com/lms`, thus we can safely assume an enterprise slug (which is taken from the URL) is always present, and use it in this redirect logic thus reducing a step.

As for the other comments- I think it's possible outside of expected onboarding flows/contexts that this redirect might be hit. My understanding is it runs whenever an unauthenticated user tries to access an authenticated page in the MFE.

Example: a coworker shares you a link, you are not logged in. This redirect would then be triggered which points to the incorrect url/proxy login.

@Alain1405 I think this is a QA fix. When references to onboarding/routing was fixed, we missed this function.

**Review by weaverjess — APPROVED** [review]

**Pull request merged**
